
# Guia Completo de PyCaret com 5 Exemplos

## O que é PyCaret?

PyCaret é uma biblioteca low-code de Machine Learning para Python.

Ela automatiza:
- treinamento;
- comparação de modelos;
- preprocessamento;
- previsão;
- análise de dados.

Com poucas linhas de código é possível criar modelos completos.


# Instalação

```python
pip install pycaret
```

ou:

```python
pip install pycaret[full]
```


# Exemplo 1 - Classificação

## Objetivo
Prever categorias.

Exemplos:
- spam;
- fraude;
- aprovação de crédito.

In [2]:
! pip install pycaret

Requirement already satisfied: pycaret in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (9.13.0)
Requirement already satisfied: ipywidgets>=7.6.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (8.1.8)
Requirement already satisfied: tqdm>=4.62.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (4.67.3)
Requirement already satisfied: numpy<1.27,>=1.21 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: scikit-learn>1.4.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.4.0)
Requirement already satisfied: imbalanced-learn>=0.12.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.14.1)
Requirement already satisfied: category-encoders>=2.4.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.62.1)
Requirement already satisfied: requests>=2.27.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.34.2)
Requirement already satisfied: psutil>=5.9.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (7.2.2)
Requirement already satisfied: markupsafe>=2.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.0.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (9.0.0)
Requirement already satisfied: nbformat>=4.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (5.10.4)
Requirement already satisfied: cloudpickle in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.7.0)
Requirement already satisfied: matplotlib<3.8.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (6.7.0)
Requirement already satisfied: kaleido>=0.2.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.3.0)
Requirement already satisfied: schemdraw==0.15 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.14.6)
Requirement already satisfied: sktime==0.26.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from sktime==0.26.0->pycaret) (26.0)
Requirement already satisfied: scikit-base<0.8.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (4.63.0)
Requirement already satisfied: kiwisolver>=1.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (1.5.0)
Requirement already satisfied: pillow>=6.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (12.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pandas<2.2.0->pycaret) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pandas<2.2.0->pycaret) (2026.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from scikit-learn>1.4.0->pycaret) (3.6.0)
Requirement already satisfied: patsy>=0.5.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (0.1.5)
Requirement already satisfied: zipp>=3.20 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (4.1.0)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (5.15.0)
Requirement already satisfied: typing_extensions>=4.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (4.15.0)
Requirement already satisfied: wcwidth in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->pycaret) (0.7.0)
Requirement already satisfied: comm>=0.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jedi>=0.18.2->ipython>=5.5.0->pycaret) (0.8.7)
Requirement already satisfied: choreographer>=1.3.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from kaleido>=0.2.1->pycaret) (1.3.0)
Requirement already satisfied: logistro>=1.0.8 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from kaleido>=0.2.1->pycaret) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from kaleido>=0.2.1->pycaret) (3.11.9)
Requirement already satisfied: platformdirs>=4.3.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from choreographer>=1.3.0->kaleido>=0.2.1->pycaret) (4.9.6)
Requirement already satisfied: simplejson>=3.19.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from choreographer>=1.3.0->kaleido>=0.2.1->pycaret) (4.1.1)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from nbformat>=4.2.0->pycaret) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from nbformat>=4.2.0->pycaret) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from nbformat>=4.2.0->pycaret) (5.9.1)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from numba>=0.55.0->pycaret) (0.45.1)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from plotly>=5.14.0->pycaret) (2.21.2)
Requirement already satisfied: dash>=2.11.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (4.1.0)
Requirement already satisfied: tsdownsample>=0.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: Flask<3.2,>=1.0.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.3)
Requirement already satisfied: Werkzeug<3.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.8)
Requirement already satisfied: retrying in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.2)
Requirement already satisfied: nest-asyncio in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: setuptools in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (82.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: click>=8.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.4.1)
Requirement already satisfied: blinker>=1.6.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.5)
Requirement already satisfied: urllib3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pmdarima>=2.0.4->pycaret) (1.26.20)
Requirement already satisfied: six>=1.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from requests>=2.27.1->pycaret) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from requests>=2.27.1->pycaret) (3.16)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from requests>=2.27.1->pycaret) (2026.5.20)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (0.2.3)

In [3]:
! pip install pycaret[full]

Requirement already satisfied: pycaret[full] in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (9.13.0)
Requirement already satisfied: ipywidgets>=7.6.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (8.1.8)
Requirement already satisfied: tqdm>=4.62.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.67.3)
Requirement already satisfied: numpy<1.27,>=1.21 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.1.4)
Requirement already satisfied: jinja2>=3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.3.2)
Requirement already satisfied: scikit-learn>1.4.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.4.0)
Requirement already satisfied: imbalanced-learn>=0.12.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.14.1)
Requirement already satisfied: category-encoders>=2.4.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.62.1)
Requirement already satisfied: requests>=2.27.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.34.2)
Requirement already satisfied: psutil>=5.9.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (7.2.2)
Requirement already satisfied: markupsafe>=2.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.0.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (9.0.0)
Requirement already satisfied: nbformat>=4.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (5.10.4)
Requirement already satisfied: cloudpickle in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.1.0)
Requirement already satisfied: xxhash in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.7.0)
Requirement already satisfied: matplotlib<3.8.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.5)
Requirement already satisfied: plotly>=5.14.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (6.7.0)
Requirement already satisfied: kaleido>=0.2.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.3.0)
Requirement already satisfied: schemdraw==0.15 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.14.6)
Requirement already satisfied: sktime==0.26.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.0.4)
Requirement already satisfied: shap~=0.44.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.44.1)
Requirement already satisfied: interpret>=0.2.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.6.9)
Requirement already satisfied: umap-learn>=0.5.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.5.7)
Requirement already satisfied: pyyaml in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (6.0.3)
Requirement already satisfied: ydata-profiling>=4.3.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.18.4)
Requirement already satisfied: explainerdashboard>=0.3.8 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.5.8)
Requirement already satisfied: fairlearn==0.7.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.7.0)
Requirement already satisfied: kmodes>=0.11.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.12.2)
Requirement already satisfied: mlxtend>=0.19.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.23.4)
Requirement already satisfied: statsforecast<1.6.0,>=0.5.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.5.0)
Requirement already satisfied: hyperopt>=0.2.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.2.7)
Requirement already satisfied: optuna>=3.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.8.0)
Requirement already satisfied: optuna-integration in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.8.0)
Requirement already satisfied: scikit-optimize>=0.9.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.10.2)
Requirement already satisfied: mlflow>=2.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (3.12.0)
Requirement already satisfied: gradio>=3.50.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (6.14.0)
Requirement already satisfied: boto3>=1.24.56 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.43.14)
Requirement already satisfied: fastapi in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.136.3)
Requirement already satisfied: uvicorn>=0.17.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.48.0)
Requirement already satisfied: m2cgen>=0.9.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.10.0)
Requirement already satisfied: evidently~=0.4.16 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.4.40)
Requirement already satisfied: dask>=2024.4.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2026.3.0)
Requirement already satisfied: distributed>=2024.4.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2026.3.0)
Requirement already satisfied: fugue~=0.8.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (0.8.7)
Requirement already satisfied: flask in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.3.3)
Requirement already satisfied: Werkzeug<3.0,>=2.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2.3.8)
Requirement already satisfied: pytest<8.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (7.4.4)
Requirement already satisfied: moto<5.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.2.14)
Requirement already satisfied: dash[testing] in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (4.1.0)
Requirement already satisfied: scikit-learn-intelex>=2023.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (2026.0.0)
Requirement already satisfied: catboost>=0.23.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret[full]) (1.2.10)
Requirement already satisfied: packaging in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from sktime==0.26.0->pycaret[full]) (26.0)
Requirement already satisfied: scikit-base<0.8.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from sktime==0.26.0->pycaret[full]) (0.7.8)
Requirement already satisfied: nltk>=3.6.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (3.9.4)
Requirement already satisfied: pydantic>=1.10.13 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (2.13.4)
Requirement already satisfied: litestar>=2.8.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (2.22.0)
Requirement already satisfied: typing-inspect>=0.9.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (0.9.0)
Requirement already satisfied: watchdog>=3.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (6.0.0)
Requirement already satisfied: typer>=0.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (0.25.1)
Requirement already satisfied: rich>=13 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (15.0.0)
Requirement already satisfied: iterative-telemetry>=0.0.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (0.0.10)
Requirement already satisfied: dynaconf>=3.2.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (3.2.13)
Requirement already satisfied: certifi>=2024.7.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (2026.5.20)
Requirement already satisfied: urllib3>=1.26.19 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (1.26.20)
Requirement already satisfied: fsspec>=2024.6.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (2026.4.0)
Requirement already satisfied: ujson>=5.4.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (5.12.1)
Requirement already satisfied: uuid6>=2024.7.10 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (2025.0.1)
Requirement already satisfied: cryptography>=43.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from evidently~=0.4.16->pycaret[full]) (46.0.7)
Requirement already satisfied: triad>=0.9.3 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from fugue~=0.8.0->pycaret[full]) (1.0.2)
Requirement already satisfied: adagio>=0.2.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from fugue~=0.8.0->pycaret[full]) (0.2.6)
Requirement already satisfied: qpd>=0.4.4 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from fugue~=0.8.0->pycaret[full]) (0.4.4)
Requirement already satisfied: fugue-sql-antlr>=0.1.6 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from fugue~=0.8.0->pycaret[full]) (0.2.2)
Requirement already satisfied: sqlglot in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from fugue~=0.8.0->pycaret[full]) (30.8.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (4.63.0)
Requirement already satisfied: kiwisolver>=1.0.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (1.5.0)
Requirement already satisfied: pillow>=6.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (12.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret[full]) (2.9.0.post0)
Requirement already satisfied: botocore>=1.12.201 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from moto<5.0.0->pycaret[full]) (1.43.14)
Requirement already satisfied: xmltodict in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from moto<5.0.0->pycaret[full]) (1.0.4)
Requirement already satisfied: responses>=0.13.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from moto<5.0.0->pycaret[full]) (0.26.1)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pandas<2.2.0->pycaret[full]) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pandas<2.2.0->pycaret[full]) (2026.2)
Requirement already satisfied: iniconfig in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pytest<8.0.0->pycaret[full]) (2.3.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pytest<8.0.0->pycaret[full]) (1.6.0)
Requirement already satisfied: colorama in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pytest<8.0.0->pycaret[full]) (0.4.6)
Requirement already satisfied: six>=1.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret[full]) (1.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from scikit-learn>1.4.0->pycaret[full]) (3.6.0)
Requirement already satisfied: slicer==0.0.7 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from shap~=0.44.0->pycaret[full]) (0.0.7)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from boto3>=1.24.56->pycaret[full]) (1.1.0)
Requirement already satisfied: s3transfer<0.18.0,>=0.17.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from boto3>=1.24.56->pycaret[full]) (0.17.0)
Requirement already satisfied: graphviz in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from catboost>=0.23.2->pycaret[full]) (0.21)
Requirement already satisfied: patsy>=0.5.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from category-encoders>=2.4.0->pycaret[full]) (1.0.2)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from cryptography>=43.0.1->evidently~=0.4.16->pycaret[full]) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from cffi>=2.0.0->cryptography>=43.0.1->evidently~=0.4.16->pycaret[full]) (3.0)
Requirement already satisfied: click>=8.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dask>=2024.4.1->pycaret[full]) (8.4.1)
Requirement already satisfied: partd>=1.4.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dask>=2024.4.1->pycaret[full]) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dask>=2024.4.1->pycaret[full]) (1.1.0)
Requirement already satisfied: locket>=1.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from distributed>=2024.4.1->pycaret[full]) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from distributed>=2024.4.1->pycaret[full]) (1.1.2)
Requirement already satisfied: sortedcontainers>=2.0.5 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from distributed>=2024.4.1->pycaret[full]) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from distributed>=2024.4.1->pycaret[full]) (3.2.2)
Requirement already satisfied: tornado>=6.2.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from distributed>=2024.4.1->pycaret[full]) (6.5.5)
Requirement already satisfied: zict>=3.0.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from distributed>=2024.4.1->pycaret[full]) (3.0.0)
Requirement already satisfied: dash-auth in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (2.3.0)
Requirement already satisfied: dash-bootstrap-components<3.0,>=1.6.0 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (2.0.4)
Requirement already satisfied: dtreeviz>=2.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (2.3.2)
Requirement already satisfied: flask-simplelogin in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (0.3.0)
Requirement already satisfied: flask-wtf>=1.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (1.3.0)
Requirement already satisfied: jupyter-dash>=0.4.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (0.4.2)
Requirement already satisfied: oyaml in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (1.0)
Requirement already satisfied: waitress in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from explainerdashboard>=0.3.8->pycaret[full]) (3.0.2)
Requirement already satisfied: typing_extensions>=4.1.1 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash[testing]->pycaret[full]) (4.15.0)
Requirement already satisfied: retrying in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash[testing]->pycaret[full]) (1.4.2)
Requirement already satisfied: nest-asyncio in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash[testing]->pycaret[full]) (1.6.0)
Requirement already satisfied: setuptools in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash[testing]->pycaret[full]) (82.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from flask->pycaret[full]) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from flask->pycaret[full]) (1.9.0)
Requirement already satisfied: colour in C:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dtreeviz>=2.1->explainerdashboard>=0.3.8->pycaret[full]) (0.1.5)

In [4]:
import sys

!{sys.executable} -m pip install pycaret

Requirement already satisfied: pycaret in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (9.13.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (8.1.8)
Requirement already satisfied: tqdm>=4.62.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (4.67.3)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: scikit-learn>1.4.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.4.0)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.14.1)
Requirement already satisfied: category-encoders>=2.4.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.62.1)
Requirement already satisfied: requests>=2.27.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.34.2)
Requirement already satisfied: psutil>=5.9.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (7.2.2)
Requirement already satisfied: markupsafe>=2.0.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.0.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (9.0.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (5.10.4)
Requirement already satisfied: cloudpickle in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.7.0)
Requirement already satisfied: matplotlib<3.8.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (6.7.0)
Requirement already satisfied: kaleido>=0.2.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.3.0)
Requirement already satisfied: schemdraw==0.15 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.14.6)
Requirement already satisfied: sktime==0.26.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from sktime==0.26.0->pycaret) (26.0)
Requirement already satisfied: scikit-base<0.8.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (4.63.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (1.5.0)
Requirement already satisfied: pillow>=6.2.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (12.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from matplotlib<3.8.0->pycaret) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pandas<2.2.0->pycaret) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pandas<2.2.0->pycaret) (2026.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from scikit-learn>1.4.0->pycaret) (3.6.0)
Requirement already satisfied: patsy>=0.5.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (0.1.5)
Requirement already satisfied: zipp>=3.20 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (4.1.0)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (5.15.0)
Requirement already satisfied: typing_extensions>=4.6 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipython>=5.5.0->pycaret) (4.15.0)
Requirement already satisfied: wcwidth in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->pycaret) (0.7.0)
Requirement already satisfied: comm>=0.1.3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jedi>=0.18.2->ipython>=5.5.0->pycaret) (0.8.7)
Requirement already satisfied: choreographer>=1.3.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from kaleido>=0.2.1->pycaret) (1.3.0)
Requirement already satisfied: logistro>=1.0.8 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from kaleido>=0.2.1->pycaret) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from kaleido>=0.2.1->pycaret) (3.11.9)
Requirement already satisfied: platformdirs>=4.3.6 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from choreographer>=1.3.0->kaleido>=0.2.1->pycaret) (4.9.6)
Requirement already satisfied: simplejson>=3.19.3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from choreographer>=1.3.0->kaleido>=0.2.1->pycaret) (4.1.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from nbformat>=4.2.0->pycaret) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from nbformat>=4.2.0->pycaret) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from nbformat>=4.2.0->pycaret) (5.9.1)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from numba>=0.55.0->pycaret) (0.45.1)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from plotly>=5.14.0->pycaret) (2.21.2)
Requirement already satisfied: dash>=2.11.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (4.1.0)
Requirement already satisfied: tsdownsample>=0.1.3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: Flask<3.2,>=1.0.4 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.3)
Requirement already satisfied: Werkzeug<3.2 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.8)
Requirement already satisfied: retrying in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: setuptools in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (82.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.4.1)
Requirement already satisfied: blinker>=1.6.2 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.5)
Requirement already satisfied: urllib3 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from pmdarima>=2.0.4->pycaret) (1.26.20)
Requirement already satisfied: six>=1.5 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from requests>=2.27.1->pycaret) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from requests>=2.27.1->pycaret) (3.16)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from requests>=2.27.1->pycaret) (2026.5.20)
Requirement already satisfied: executing>=1.2.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\Olive\Anaconda\envs\pycaret311\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (0.2.3)

In [5]:
from pycaret.classification import *
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

base = pd.DataFrame(iris.data, columns=iris.feature_names)
base['target'] = iris.target

base.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [6]:
clf = setup(data=base, target='target', session_id=123)

In [7]:
melhor_modelo = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              20:12:47
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [8]:
modelo_rf = create_model('rf')

In [9]:
predicoes = predict_model(modelo_rf)
predicoes.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,prediction_label,prediction_score
72,6.3,2.5,4.9,1.5,1,2,0.57
125,7.2,3.2,6.0,1.8,2,2,0.91
80,5.5,2.4,3.8,1.1,1,1,1.00
86,6.7,3.1,4.7,1.5,1,1,1.00
117,7.7,3.8,6.7,2.2,2,2,0.99


# Exemplo 2 - Regressão

## Objetivo
Prever valores numéricos.

In [10]:
from pycaret.regression import *
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing(as_frame=True)

base_reg = housing.frame

base_reg.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [11]:
reg = setup(data=base_reg, target='MedHouseVal', session_id=123)

In [12]:
melhor_regressor = compare_models()

In [13]:
modelo_reg = create_model('rf')


# Exemplo 3 - Clustering

## Objetivo
Agrupar dados semelhantes.

In [14]:
from pycaret.clustering import *
from sklearn.datasets import load_wine

wine = load_wine(as_frame=True)

base_cluster = wine.frame

base_cluster.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [15]:
cluster = setup(
    data = base_cluster,
    session_id=123
)

In [16]:
kmeans = create_model('kmeans')

Initiated  . . . . . . . . . . . . . . . . . .            20:17:57
Status     . . . . . . . . . . . . . . . . . .  Fitting 4 Clusters
Estimator  . . . . . . . . . . . . . . . . . .  K-Means Clustering

In [17]:
resultado_cluster = assign_model(kmeans)
resultado_cluster.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target,Cluster
0,14.23,1.71,2.43,15.600000,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0,Cluster 1
1,13.20,1.78,2.14,11.200000,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0,Cluster 1
2,13.16,2.36,2.67,18.600000,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0,Cluster 1
3,14.37,1.95,2.50,16.799999,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0,Cluster 3
4,13.24,2.59,2.87,21.000000,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0,Cluster 2


# Exemplo 4 - Detecção de Anomalias

## Objetivo
Detectar comportamentos incomuns.

In [18]:
from pycaret.anomaly import *

anomalia = setup(
    data = base_cluster,
    session_id=123
)