# Agrupamento

In [3]:
!pip install plotly

Requirement already satisfied: plotly in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from plotly) (2.18.0)
Requirement already satisfied: packaging in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from plotly) (24.0)

In [4]:
!pip install plotly --upgrade

Requirement already satisfied: plotly in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from plotly) (2.18.0)
Requirement already satisfied: packaging in c:\Users\Olive\AppData\Local\Programs\Python\Python312\Lib\site-packages (from plotly) (24.0)

In [7]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

### K-means

## Base idade e salário

In [8]:
from sklearn.cluster import KMeans

In [9]:
from sklearn.cluster import KMeans

In [10]:
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

In [11]:
grafico = px.scatter(x = x,y = y)
grafico.show()

In [12]:
base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

In [13]:
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [14]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [15]:
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [16]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [17]:
centroides = kmeans_salario.cluster_centers_
centroides

array([[-1.301881  , -0.75688568],
       [ 0.07703438,  1.11413572],
       [ 0.94906354, -0.73145432]])

In [19]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  26.25      , 1737.5       ],
       [  41.16666667, 5600.        ],
       [  50.6       , 1790.        ]])

In [20]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  26.25      , 1737.5       ],
       [  41.16666667, 5600.        ],
       [  50.6       , 1790.        ]])

In [21]:
rotulos = kmeans_salario.labels_
rotulos

array([0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1])

In [23]:
grafico1 = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color=rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size= [12,12,12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico1.show()

### Dados randômicos

In [24]:
from sklearn.datasets import make_blobs

In [25]:
X_random, y_random = make_blobs(n_samples = 200, centers=5, random_state=1)

In [26]:
X_random

array([[-1.96576392e+00,  5.23446451e+00],
       [-5.16022348e+00, -7.04217141e+00],
       [-6.17937069e+00, -2.16733539e+00],
       [-7.39138168e+00, -9.49590389e+00],
       [-6.38481234e+00, -8.47302970e+00],
       [-6.26144310e+00, -3.78347905e+00],
       [-2.04278768e+00,  3.07660864e-01],
       [-4.46426086e+00, -4.39451238e+00],
       [-6.40386190e+00, -6.36106990e+00],
       [ 2.42271161e-04,  5.14853403e+00],
       [-5.99212006e+00, -3.91488289e+00],
       [-6.46137477e+00, -3.14560994e+00],
       [-4.10185174e+00, -1.16625450e+00],
       [-1.01341572e+01, -4.07240274e+00],
       [-5.99004766e+00, -2.82631801e+00],
       [-1.14663009e+00,  4.10839703e+00],
       [-1.17104176e+00,  4.33091816e+00],
       [-9.19585147e+00, -3.90678125e+00],
       [-8.30173556e+00, -7.27738918e+00],
       [-7.56309575e+00, -8.46421308e+00],
       [-1.86845414e+00,  4.99311306e+00],
       [-4.22362233e+00, -2.50312346e+00],
       [-1.90838667e+00,  5.86113655e-01],
       [-6.52897564e+00, -1.68894152e+00],
       [-3.08653646e+00,  1.57086292e+00],
       [-9.46824718e+00, -3.81564734e+00],
       [-6.25393051e+00, -7.10878601e+00],
       [-3.06167031e+00,  6.69540693e-01],
       [-2.50687979e+00,  1.09986203e+00],
       [-1.01786328e+01, -4.55726918e+00],
       [-7.92619854e+00, -7.47851658e+00],
       [-2.51338855e+00,  1.03886641e-01],
       [-1.61734616e+00,  4.98930508e+00],
       [-5.99829647e+00, -3.82205706e+00],
       [-8.73907799e+00, -7.32819828e+00],
       [-1.85139546e+00,  3.51886090e+00],
       [-8.72395657e+00, -1.98624680e+00],
       [-7.76528069e+00, -8.35662255e+00],
       [-9.87589123e+00, -2.82386464e+00],
       [-2.10001844e+00,  2.88693973e+00],
       [-8.28462658e+00, -5.70385946e+00],
       [-9.15155186e+00, -4.81286449e+00],
       [-2.30108747e+00,  1.50414818e+00],
       [-1.21136929e+00,  3.63305370e-01],
       [-8.71560345e+00, -9.04378369e+00],
       [-1.44666498e+00,  5.92158354e-01],
       [-1.01842823e+01, -4.05509442e+00],
       [-7.39126579e+00, -3.00785836e+00],
       [-6.07854700e+00, -7.93969420e+00],
       [-1.34392496e+00,  2.38428865e+00],
       [-1.78245013e+00,  3.47072043e+00],
       [-5.65299227e+00, -3.68858999e+00],
       [-7.15207729e+00, -3.95657268e+00],
       [-1.98197711e+00,  4.02243551e+00],
       [-7.23022103e+00, -2.50287503e+00],
       [-9.50250118e+00, -4.12805171e+00],
       [ 8.52518583e-02,  3.64528297e+00],
       [-4.57109117e+00, -1.33782924e+00],
       [-5.65734218e+00, -8.02412652e+00],
       [-7.18534676e+00, -9.38634884e+00],
       [-9.59422086e+00, -3.35977002e+00],
       [-7.05670746e+00, -3.52629444e+00],
       [-5.47976968e+00, -3.46322378e+00],
       [-5.65625664e+00, -3.53195739e+00],
       [-5.50607664e+00, -8.04382541e+00],
       [-1.97451969e-01,  2.34634916e+00],
       [-1.35938959e+00,  4.05424002e+00],
       [-9.47713617e+00, -5.09768994e+00],
       [-2.47628968e+00,  2.05486276e+00],
       [-6.50212109e+00, -7.91249101e+00],
       [-1.00223295e+01, -4.72851017e+00],
       [-1.21194645e+00,  8.11694777e-01],
       [-5.95049921e+00, -8.73975204e+00],
       [-3.60344376e+00,  3.28439495e-01],
       [-6.13221255e-01,  1.58297832e-01],
       [-1.03415662e+01, -3.90975169e+00],
       [-6.56169737e+00, -6.86000222e+00],
       [-9.06788077e+00, -1.15125665e+00],
       [-2.34673261e+00,  3.56128423e+00],
       [ 7.31775521e-02, -9.19931685e-03],
       [-8.95888790e+00, -1.76636890e+00],
       [-1.02639310e+01, -3.92073400e+00],
       [-5.90846376e+00, -4.13337484e+00],
       [-6.40583239e+00, -9.78066645e+00],
       [-7.00039289e+00, -3.95655414e+00],
       [-1.83198811e+00,  3.52863145e+00],
       [-8.33744094e+00, -7.83968038e+00],
       [-7.61065635e+00, -8.35206597e+00],
       [-8.24720031e+00, -8.81898262e+00],
       [-9.55634806e+00, -4.05350378e+00],
       [-2.29932889e-01,  1.34071754e+00],
       [-5.43879105e+00, -1.54542635e+00],
       [-1.92744799e+00,  4.93684534e+00],
       [-2.48750748e+00,  8.62799087e-01],
       [-6.61978298e+00, -3.31962520e+00],
       [-9.98030310e+00, -5.07536728e+00],
       [-1.05452334e+00,  1.69635261e+00],
       [-7.57969185e-01,  4.90898421e+00],
       [-5.90454361e+00, -7.78373539e+00],
       [-8.87629480e+00, -3.54444801e+00],
       [-2.41395785e+00,  5.65935802e+00],
       [-4.53655648e+00, -8.40186288e+00],
       [-3.37118459e+00,  8.52715160e-01],
       [-9.64716652e+00, -5.26563196e+00],
       [-2.54002339e+00,  1.25394486e+00],
       [-6.44152001e+00, -8.58818479e+00],
       [-9.74891334e+00, -4.24998970e+00],
       [-7.02121319e+00, -8.37954235e+00],
       [-5.51599011e+00, -2.20387664e+00],
       [ 5.26015501e-01,  3.00999353e+00],
       [-3.24393866e+00, -2.26420083e+00],
       [-6.41077310e+00, -3.88605524e+00],
       [-8.18399758e+00, -6.19714920e+00],
       [-1.18556944e+01, -2.71718452e+00],
       [-5.84526963e+00, -3.69578386e+00],
       [-2.80207810e+00,  4.05714715e+00],
       [-1.12277706e+01, -3.40281105e+00],
       [-3.82057616e+00,  1.49112428e+00],
       [-5.25790464e-01,  3.30659860e+00],
       [-7.58703957e-01,  3.72276201e+00],
       [-6.78421711e+00, -8.22634081e+00],
       [-9.57421815e+00, -3.87600848e+00],
       [-1.06177133e+01, -3.25531651e+00],
       [-4.20901245e+00, -4.55994238e+00],
       [-1.53940095e+00,  5.02369298e+00],
       [-9.76521794e+00, -3.27079714e+00],
       [-6.46256290e+00, -7.73294590e+00],
       [-2.25970786e+00,  1.58172810e+00],
       [-4.87418245e+00, -1.00495890e+01],
       [-4.00797392e+00,  1.12882904e+00],
       [-5.27930518e-01,  5.92630669e+00],
       [-1.54957690e+00, -2.00619979e+00],
       [-4.88601638e+00, -3.75012970e+00],
       [-6.21404558e+00, -2.87766070e+00],
       [-1.03729975e+01, -4.59207895e+00],
       [-9.25715605e+00, -4.90704915e+00],
       [-7.10496767e+00, -3.96936306e+00],
       [-2.76017908e+00,  5.55121358e+00],
       [-3.10367371e+00,  3.90202401e+00],
       [-5.15138361e+00, -2.78351842e+00],
       [-6.35930380e+00, -3.38614734e+00],
       [-5.85749377e+00, -2.30401481e+00],
       [-1.88188805e+00,  4.20573180e+00],
       [-2.77687025e+00,  4.64090557e+00],
       [-2.62214524e+00,  1.71550342e+00],
       [-7.62718761e+00, -6.19835003e+00],
       [-3.49120594e+00,  2.54429463e+00],
       [-2.40671820e+00,  6.09894447e+00],
       [-6.82221274e+00, -7.95139793e+00],
       [-6.25826821e+00, -2.91159774e+00],
       [-3.93781149e+00,  1.69694980e+00],
       [-5.65371307e+00, -2.13266376e+00],
       [-1.34052081e+00,  4.15711949e+00],
       [-2.18063570e+00,  6.00875711e-01],
       [-6.55389349e+00, -1.46593637e+00],
       [-1.04448411e+01, -2.72884084e+00],
       [-8.79879462e+00, -3.76819213e+00],
       [-9.20490564e+00, -4.57687928e+00],
       [-1.60875215e+00,  3.76949422e+00],
       [-7.17532921e+00, -8.77059017e+00],
       [-1.62648417e+00,  1.89866300e+00],
       [-1.47299851e+00,  4.81654152e+00],
       [-1.13708298e+01, -3.63818916e+00],
       [-1.46864442e+00,  6.50674501e+00],
       [-2.99856517e+00,  2.43314354e-01],
       [-9.91989138e+00, -3.33496829e+00],
       [-8.37006175e+00, -3.61533685e+00],
       [-1.06683748e+01, -3.57578476e+00],
       [-5.78245922e+00, -3.76946360e+00],
       [-2.23284936e+00,  6.02154336e-01],
       [-1.00364080e+01, -5.56912090e+00],
       [-1.69741870e+00,  2.00923387e+00],
       [-2.17464201e+00,  7.84883626e-01],
       [-6.14074758e+00, -1.88673060e+00],
       [-8.20576492e-01,  5.33759195e+00],
       [-8.39683385e+00, -9.91391667e+00],
       [-1.48000390e+00,  1.10060892e+00],
       [-6.16857305e+00, -4.61446578e+00],
       [-7.71179887e+00, -7.25174121e+00],
       [-1.37397258e+00,  5.29163103e+00],
       [-7.06677367e+00, -9.54984853e+00],
       [-2.35122066e+00,  4.00973634e+00],
       [-1.42946517e+00,  5.16850105e+00],
       [-5.73342507e+00, -8.44053597e+00],
       [-1.11969805e+01, -3.09000323e+00],
       [-1.60348642e+00, -3.99647991e-01],
       [-1.05148070e+01, -4.95037538e+00],
       [-2.33080604e+00,  4.39382527e+00],
       [-1.49952284e+00,  5.28265879e+00],
       [-7.71567180e+00, -1.85653239e+00],
       [-7.46576038e+00, -7.32922249e+00],
       [-2.77049102e+00,  1.96902075e+00],
       [-1.46126019e+00,  4.52549851e+00],
       [-9.12882635e+00, -3.20293691e+00],
       [-1.03078293e+01, -6.38818631e+00],
       [-2.30259245e+00,  1.93162257e+00],
       [-5.62021562e+00, -3.13997391e+00],
       [-2.76599494e+00,  2.39111656e-01],
       [-5.44793258e+00, -7.65048722e+00],
       [-1.10926243e+01, -3.78396611e+00]])

In [27]:
y_random

array([0, 2, 3, 2, 2, 3, 4, 3, 2, 0, 3, 3, 4, 1, 3, 0, 0, 1, 2, 2, 0, 3,
       4, 3, 4, 1, 2, 4, 4, 1, 2, 4, 0, 3, 2, 0, 1, 2, 1, 4, 2, 1, 4, 4,
       2, 4, 1, 3, 2, 0, 0, 3, 3, 0, 3, 1, 0, 4, 2, 2, 1, 3, 3, 3, 2, 0,
       0, 1, 4, 2, 1, 4, 2, 4, 4, 1, 2, 3, 0, 4, 1, 1, 3, 2, 3, 0, 2, 2,
       2, 1, 4, 3, 0, 4, 3, 1, 4, 0, 2, 1, 0, 2, 4, 1, 4, 2, 1, 2, 3, 0,
       3, 3, 2, 1, 3, 0, 1, 4, 0, 0, 2, 1, 1, 3, 0, 1, 2, 4, 2, 4, 0, 4,
       3, 3, 1, 1, 3, 0, 0, 3, 3, 3, 0, 0, 4, 2, 4, 0, 2, 3, 4, 3, 0, 4,
       3, 1, 1, 1, 0, 2, 4, 0, 1, 0, 4, 1, 1, 1, 3, 4, 1, 4, 4, 3, 0, 2,
       4, 3, 2, 0, 2, 0, 0, 2, 1, 4, 1, 0, 0, 3, 2, 4, 0, 1, 1, 4, 3, 4,
       2, 1])

In [28]:
grafico = px.scatter(x = X_random[:,0], y = X_random[:,1])
grafico.show()

In [29]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(n_clusters=5)

In [30]:
rotulos = kmeans_blobs.predict(X_random)
rotulos

array([4, 2, 0, 2, 2, 0, 1, 0, 2, 4, 0, 0, 0, 3, 0, 4, 4, 3, 2, 2, 4, 0,
       1, 0, 1, 3, 2, 1, 1, 3, 2, 1, 4, 0, 2, 4, 3, 2, 3, 4, 3, 3, 1, 1,
       2, 1, 3, 0, 2, 1, 4, 0, 0, 4, 0, 3, 4, 0, 2, 2, 3, 0, 0, 0, 2, 1,
       4, 3, 1, 2, 3, 1, 2, 1, 1, 3, 2, 3, 4, 1, 3, 3, 0, 2, 0, 4, 2, 2,
       2, 3, 1, 0, 4, 1, 0, 3, 1, 4, 2, 3, 4, 2, 1, 3, 1, 2, 3, 2, 0, 4,
       0, 0, 2, 3, 0, 4, 3, 1, 4, 4, 2, 3, 3, 0, 4, 3, 2, 1, 2, 1, 4, 1,
       0, 0, 3, 3, 0, 4, 4, 0, 0, 0, 4, 4, 1, 2, 1, 4, 2, 0, 1, 0, 4, 1,
       0, 3, 3, 3, 4, 2, 1, 4, 3, 4, 1, 3, 3, 3, 0, 1, 3, 1, 1, 0, 4, 2,
       1, 0, 2, 4, 2, 4, 4, 2, 3, 1, 3, 4, 4, 0, 2, 1, 4, 3, 3, 1, 0, 1,
       2, 3])

In [32]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[-5.90368078, -3.04489641],
       [-2.17069756,  1.02591979],
       [-6.87958999, -8.11648104],
       [-9.85620522, -3.91021738],
       [-1.58338528,  4.50520457]])

In [34]:
grafico1 = px.scatter(x = X_random[:,0], y = X_random[:,1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [5,5,5,5,5])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

### Base de dados cartão de crédito - 1 atributo

- Fonte: https://archive.ics.edu/ml/datasets/default+of+credit+card+clients

In [37]:
import pandas as pd
base_cartao = pd.read_csv('credit_card_clients.csv', header = 1)
base_cartao

          ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0          1      20000    2  ...         0         0                           1
1          2     120000    2  ...         0      2000                           1
2          3      90000    2  ...      1000      5000                           0
3          4      50000    2  ...      1069      1000                           0
4          5      50000    1  ...       689       679                           0
...      ...        ...  ...  ...       ...       ...                         ...
29995  29996     220000    1  ...      5000      1000                           0
29996  29997     150000    1  ...         0         0                           0
29997  29998      30000    1  ...      2000      3100                           1
29998  29999      80000    1  ...     52964      1804                           1
29999  30000      50000    1  ...      1000      1000                           1

[30000 rows x 25 columns]

In [38]:
base_cartao['BILL_TOTAL'] = base_cartao['BILL_AMT1'] + base_cartao['BILL_AMT2'] + base_cartao['BILL_AMT3'] + base_cartao['BILL_AMT4'] + base_cartao['BILL_AMT5'] + base_cartao['BILL_AMT6']

In [39]:
base_cartao

          ID  LIMIT_BAL  SEX  ...  PAY_AMT6  default payment next month  BILL_TOTAL
0          1      20000    2  ...         0                           1        7704
1          2     120000    2  ...      2000                           1       17077
2          3      90000    2  ...      5000                           0      101653
3          4      50000    2  ...      1000                           0      231334
4          5      50000    1  ...       679                           0      109339
...      ...        ...  ...  ...       ...                         ...         ...
29995  29996     220000    1  ...      1000                           0      725349
29996  29997     150000    1  ...         0                           0       21182
29997  29998      30000    1  ...      3100                           1       70496
29998  29999      80000    1  ...      1804                           1      266611
29999  30000      50000    1  ...      1000                           1      230874

[30000 rows x 26 columns]

In [40]:
X_cartao = base_cartao.iloc[:,[1,25]].values
X_cartao

array([[ 20000,   7704],
       [120000,  17077],
       [ 90000, 101653],
       ...,
       [ 30000,  70496],
       [ 80000, 266611],
       [ 50000, 230874]], dtype=int64)

In [41]:
scaler_cartao = StandardScaler()
X_cartao = scaler_cartao.fit_transform(X_cartao)

In [42]:
X_cartao

array([[-1.13672015, -0.69069198],
       [-0.3659805 , -0.66599747],
       [-0.59720239, -0.44316987],
       ...,
       [-1.05964618, -0.52525745],
       [-0.67427636, -0.00856436],
       [-0.90549825, -0.10271861]])